version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - elastic
    environment:
      DATABASE_URI: "postgresql://postgres:P@ssw0rd!@db/postgres"
      ELASTIC_URI: "http://elastic"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
